### ISSUE TITLE
Use did:key for the issuer key?

### ISSUE THREAD

**Issue by swcurran** [TimoGlastra/anoncreds-w3c-test-vectors#1]
On [this line](https://github.com/TimoGlastra/anoncreds-w3c-test-vectors/blob/e8b8a7f656d3005abd3ff769a0665de6e4e8345f/test-vectors/eddsa-issuer-key.json#L4), and others in the test vectors we use “did:example:123” for the issuer DID.

For test vectors, wouldn’t make more sense to use a real did:key DID for the issuer key?

**Comment by TimoGlastra** [comment]
Yes we can update to did:key
